/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RouterHistory } from "@stencil/router";
import { Statement } from "./data/stress-type.interface";
import { RatingClickEvent } from "./components/pages/statement-evaluation-page/statement-evaluation-page.interface";
export namespace Components {
    interface AppRoot {
        "history": RouterHistory;
    }
    interface PeButton {
    }
    interface PeCard {
    }
    interface PeNotFoundPage {
    }
    interface PeStatementEvaluationPage {
        "statement": Statement;
    }
    interface PeStressTypeResultPage {
        "history": RouterHistory;
        "ratedStatements": Array<Statement>;
    }
    interface PeTextContainer {
    }
    interface PeWelcomePage {
        "history": RouterHistory;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLPeButtonElement extends Components.PeButton, HTMLStencilElement {
    }
    var HTMLPeButtonElement: {
        prototype: HTMLPeButtonElement;
        new (): HTMLPeButtonElement;
    };
    interface HTMLPeCardElement extends Components.PeCard, HTMLStencilElement {
    }
    var HTMLPeCardElement: {
        prototype: HTMLPeCardElement;
        new (): HTMLPeCardElement;
    };
    interface HTMLPeNotFoundPageElement extends Components.PeNotFoundPage, HTMLStencilElement {
    }
    var HTMLPeNotFoundPageElement: {
        prototype: HTMLPeNotFoundPageElement;
        new (): HTMLPeNotFoundPageElement;
    };
    interface HTMLPeStatementEvaluationPageElement extends Components.PeStatementEvaluationPage, HTMLStencilElement {
    }
    var HTMLPeStatementEvaluationPageElement: {
        prototype: HTMLPeStatementEvaluationPageElement;
        new (): HTMLPeStatementEvaluationPageElement;
    };
    interface HTMLPeStressTypeResultPageElement extends Components.PeStressTypeResultPage, HTMLStencilElement {
    }
    var HTMLPeStressTypeResultPageElement: {
        prototype: HTMLPeStressTypeResultPageElement;
        new (): HTMLPeStressTypeResultPageElement;
    };
    interface HTMLPeTextContainerElement extends Components.PeTextContainer, HTMLStencilElement {
    }
    var HTMLPeTextContainerElement: {
        prototype: HTMLPeTextContainerElement;
        new (): HTMLPeTextContainerElement;
    };
    interface HTMLPeWelcomePageElement extends Components.PeWelcomePage, HTMLStencilElement {
    }
    var HTMLPeWelcomePageElement: {
        prototype: HTMLPeWelcomePageElement;
        new (): HTMLPeWelcomePageElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "pe-button": HTMLPeButtonElement;
        "pe-card": HTMLPeCardElement;
        "pe-not-found-page": HTMLPeNotFoundPageElement;
        "pe-statement-evaluation-page": HTMLPeStatementEvaluationPageElement;
        "pe-stress-type-result-page": HTMLPeStressTypeResultPageElement;
        "pe-text-container": HTMLPeTextContainerElement;
        "pe-welcome-page": HTMLPeWelcomePageElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
        "history"?: RouterHistory;
    }
    interface PeButton {
    }
    interface PeCard {
    }
    interface PeNotFoundPage {
    }
    interface PeStatementEvaluationPage {
        "onRatingClick"?: (event: CustomEvent<RatingClickEvent>) => void;
        "statement"?: Statement;
    }
    interface PeStressTypeResultPage {
        "history"?: RouterHistory;
        "onResetState"?: (event: CustomEvent<any>) => void;
        "ratedStatements"?: Array<Statement>;
    }
    interface PeTextContainer {
    }
    interface PeWelcomePage {
        "history"?: RouterHistory;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "pe-button": PeButton;
        "pe-card": PeCard;
        "pe-not-found-page": PeNotFoundPage;
        "pe-statement-evaluation-page": PeStatementEvaluationPage;
        "pe-stress-type-result-page": PeStressTypeResultPage;
        "pe-text-container": PeTextContainer;
        "pe-welcome-page": PeWelcomePage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "pe-button": LocalJSX.PeButton & JSXBase.HTMLAttributes<HTMLPeButtonElement>;
            "pe-card": LocalJSX.PeCard & JSXBase.HTMLAttributes<HTMLPeCardElement>;
            "pe-not-found-page": LocalJSX.PeNotFoundPage & JSXBase.HTMLAttributes<HTMLPeNotFoundPageElement>;
            "pe-statement-evaluation-page": LocalJSX.PeStatementEvaluationPage & JSXBase.HTMLAttributes<HTMLPeStatementEvaluationPageElement>;
            "pe-stress-type-result-page": LocalJSX.PeStressTypeResultPage & JSXBase.HTMLAttributes<HTMLPeStressTypeResultPageElement>;
            "pe-text-container": LocalJSX.PeTextContainer & JSXBase.HTMLAttributes<HTMLPeTextContainerElement>;
            "pe-welcome-page": LocalJSX.PeWelcomePage & JSXBase.HTMLAttributes<HTMLPeWelcomePageElement>;
        }
    }
}
